name: Build ESP32 Firmware

on:
  push:
    tags:
      - 'v*'        # сборка при пуше тега типа v1.2.3
  workflow_dispatch:  # возможность запуска вручную

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - esp32
          - esp32c3
          - esp32s3
          - seeed_xiao_esp32c3

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python (для PlatformIO)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Устанавливаем PlatformIO
      - name: Install PlatformIO
        run: pip install platformio

      # 4️⃣ Сборка прошивки
      - name: Build firmware
        run: |
          cd PlatformIO
          pio run -e ${{ matrix.env }}

      # 5️⃣ Переименовываем firmware, bootloader и partitions по env
      - name: Rename firmware, bootloader and partitions
        run: |
          cd PlatformIO/.pio/build/${{ matrix.env }}
          mv firmware.bin firmware-${{ matrix.env }}.bin
          mv bootloader.bin bootloader-${{ matrix.env }}.bin
          mv partitions.bin partitions-${{ matrix.env }}.bin

      # 6️⃣ Создаём ZIP со всеми прошивками после сборки всех плат
      - name: Package all firmware into ZIP
        if: matrix.env == 'seeed_xiao_esp32c3'  # делаем только на последнем env
        run: |
          cd PlatformIO/.pio/build
          zip -r ../LS-Buttplug-${GITHUB_REF_NAME}.zip *

      # # 7️⃣ Загружаем ZIP в Release
      # - name: Upload ZIP to Release
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: PlatformIO/LS-Buttplug-${GITHUB_REF_NAME}.zip
      #     overwrite: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
